### Project 1

Project description: 
- Read data into Jupyter notebook, use pandas to import data into a data frame
- preprocess data: explore data, address missing data, categorical data, if there is any, and data scaling. Justify the type of scaling used in this project. 
- train your dataset using all the linear regression models you've learned so far. If your model has a scaling parameter(s) use Grid Search to find the best scaling parameter. Use plots and graphs to help you get a better glimpse of the results. 
- Then use cross validation to find average training and testing score. 
- Your submission should have at least the following regression models: KNN repressor, linear regression, Ridge, Lasso, polynomial regression, SVM both simple and with kernels. 
- Finally find the best repressor for this dataset and train your model on the entire dataset using the best parameters and predict the market price for the test_set.
- submit IPython notebook. Use markdown to provide an inline report for this project.

##### <font color = 'red'> Important note: All the group members should participate in completing this project.  This includes coding, preparing report and testing the models. 

In [2]:
import pandas as pd
data = pd.read_csv('bitcoin_dataset(1).csv')
final_test = pd.read_csv('test_set(1).csv')

In [3]:
data.head()

Date  btc_market_price  btc_total_bitcoins  btc_market_cap  \
0  2/17/2010 0:00               0.0           2043200.0             0.0   
1  2/18/2010 0:00               0.0           2054650.0             0.0   
2  2/19/2010 0:00               0.0           2063600.0             0.0   
3  2/20/2010 0:00               0.0           2074700.0             0.0   
4  2/21/2010 0:00               0.0           2085400.0             0.0   

   btc_trade_volume  btc_blocks_size  btc_avg_block_size  \
0               0.0              0.0            0.000235   
1               0.0              0.0            0.000241   
2               0.0              0.0            0.000228   
3               0.0              0.0            0.000218   
4               0.0              0.0            0.000234   

   btc_n_orphaned_blocks  btc_n_transactions_per_block  \
0                      0                           1.0   
1                      0                           1.0   
2                      0                           1.0   
3                      0                           1.0   
4                      0                           1.0   

   btc_median_confirmation_time                  ...                   \
0                           0.0                  ...                    
1                           0.0                  ...                    
2                           0.0                  ...                    
3                           0.0                  ...                    
4                           0.0                  ...                    

   btc_cost_per_transaction_percent  btc_cost_per_transaction  \
0                         31.781022                       0.0   
1                        154.463801                       0.0   
2                       1278.516635                       0.0   
3                      22186.687990                       0.0   
4                        689.179876                       0.0   

   btc_n_unique_addresses  btc_n_transactions  btc_n_transactions_total  \
0                     241                 244                     41240   
1                     234                 235                     41475   
2                     185                 183                     41658   
3                     224                 224                     41882   
4                     218                 218                     42100   

   btc_n_transactions_excluding_popular  \
0                                   244   
1                                   235   
2                                   183   
3                                   224   
4                                   218   

   btc_n_transactions_excluding_chains_longer_than_100  btc_output_volume  \
0                                                244             65173.13   
1                                                235             18911.74   
2                                                183              9749.98   
3                                                224             11150.03   
4                                                218             12266.83   

   btc_estimated_transaction_volume  btc_estimated_transaction_volume_usd  
0                           36500.0                                   0.0  
1                            7413.0                                   0.0  
2                             700.0                                   0.0  
3                              50.0                                   0.0  
4                            1553.0                                   0.0  

[5 rows x 24 columns]

In [3]:
final_test.head()

Date  btc_total_bitcoins  btc_market_cap  btc_trade_volume  \
0  2/1/2018 0:00          16839687.5    1.529590e+11      1.509688e+09   
1  2/2/2018 0:00          16841787.5    1.499240e+11      2.213437e+09   
2  2/3/2018 0:00          16843762.5    1.528850e+11      9.524038e+08   
3  2/4/2018 0:00          16845987.5    1.415170e+11      1.080683e+09   
4  2/5/2018 0:00          16848300.0    1.152220e+11      1.793319e+09   

   btc_blocks_size  btc_avg_block_size  btc_n_orphaned_blocks  \
0      154613.2244            1.053963                      0   
1      154785.0008            1.022479                      0   
2      154942.4583            0.996567                      0   
3      155118.7652            0.990488                      0   
4      155322.7709            1.102733                      0   

   btc_n_transactions_per_block  btc_median_confirmation_time  btc_hash_rate  \
0                   1610.400000                     12.475000    20703947.91   
1                   1404.273810                     11.225000    21739145.31   
2                   1233.487342                     10.475000    20445148.56   
3                    975.769663                      9.275000    23033142.05   
4                   1169.529730                      6.133333    23938939.78   

                   ...                   btc_cost_per_transaction_percent  \
0                  ...                                           0.799509   
1                  ...                                           0.717894   
2                  ...                                           1.290914   
3                  ...                                           1.208997   
4                  ...                                           0.967008   

   btc_cost_per_transaction  btc_n_unique_addresses  btc_n_transactions  \
0                 78.049647                  591550              257664   
1                 89.591902                  551198              235918   
2                 98.824757                  436196              194891   
3                112.999677                  396694              173687   
4                 78.586115                  486553              216363   

   btc_n_transactions_total  btc_n_transactions_excluding_popular  \
0                 296946448                                249466   
1                 297182366                                229894   
2                 297377257                                184856   
3                 297550944                                165753   
4                 297767307                                208757   

   btc_n_transactions_excluding_chains_longer_than_100  btc_output_volume  \
0                                             179686         2.190613e+06   
1                                             155128         1.460796e+06   
2                                             131568         9.100425e+05   
3                                             125143         9.722485e+05   
4                                             144850         1.848913e+06   

   btc_estimated_transaction_volume  btc_estimated_transaction_volume_usd  
0                       276923.3207                          2.515366e+09  
1                       330740.2192                          2.944217e+09  
2                       164374.0244                          1.491970e+09  
3                       193244.2140                          1.623377e+09  
4                       257109.2993                          1.758323e+09  

[5 rows x 23 columns]

In [4]:
final_test.shape

(14, 23)

In [5]:
data.shape

(2906, 24)

In [6]:
data.describe()

btc_market_price  btc_total_bitcoins  btc_market_cap  btc_trade_volume  \
count       2906.000000        2.879000e+03    2.906000e+03      2.885000e+03   
mean         839.104218        1.151138e+07    1.344255e+10      7.398381e+07   
std         2304.972497        4.200024e+06    3.866150e+10      2.924228e+08   
min            0.000000        2.043200e+06    0.000000e+00      0.000000e+00   
25%            6.653465        8.485300e+06    5.363081e+07      2.916456e+05   
50%          235.130000        1.243115e+07    3.346869e+09      1.001414e+07   
75%          594.191164        1.520051e+07    8.075525e+09      2.834038e+07   
max        19498.683330        1.683769e+07    3.265250e+11      5.352016e+09   

       btc_blocks_size  btc_avg_block_size  btc_n_orphaned_blocks  \
count      2877.000000         2906.000000            2906.000000   
mean      35505.502848            0.350366               0.364074   
std       43618.633821            0.353168               0.842259   
min           0.000000            0.000216               0.000000   
25%         781.000000            0.024177               0.000000   
50%       15183.000000            0.196022               0.000000   
75%       58293.000000            0.676065               0.000000   
max      154444.590300            1.110327               7.000000   

       btc_n_transactions_per_block  btc_median_confirmation_time  \
count                   2906.000000                   2894.000000   
mean                     671.673651                      7.501113   
std                      689.561322                      4.974549   
min                        1.000000                      0.000000   
25%                       54.000000                      6.066667   
50%                      375.000000                      7.916667   
75%                     1232.995223                     10.208333   
max                     2722.625000                     47.733333   

       btc_hash_rate                  ...                   \
count   2.906000e+03                  ...                    
mean    1.244070e+06                  ...                    
std     2.924141e+06                  ...                    
min     2.250000e-05                  ...                    
25%     1.160880e+01                  ...                    
50%     2.176189e+04                  ...                    
75%     1.035363e+06                  ...                    
max     2.160975e+07                  ...                    

       btc_cost_per_transaction_percent  btc_cost_per_transaction  \
count                       2906.000000               2906.000000   
mean                          66.747821                 14.639125   
std                         1761.894646                 20.536083   
min                            0.136531                  0.000000   
25%                            1.181945                  4.156470   
50%                            2.493564                  7.822430   
75%                            5.915591                 14.800589   
max                        88571.428570                161.686071   

       btc_n_unique_addresses  btc_n_transactions  btc_n_transactions_total  \
count            2.906000e+03         2906.000000              2.906000e+03   
mean             1.937861e+05       102081.138334              6.844558e+07   
std              2.089146e+05       103896.929350              8.285341e+07   
min              1.100000e+02          118.000000              4.124000e+04   
25%              1.675475e+04         8025.250000              2.413376e+06   
50%              1.304450e+05        62337.000000              3.255271e+07   
75%              3.603765e+05       190471.250000              1.080663e+08   
max              1.072861e+06       490644.000000              2.966888e+08   

       btc_n_transactions_excluding_popular  \
count                           2906.000000   
mean                           94348.852374   

In [7]:
data.isnull().values.any()

True

In [8]:
data.isnull().sum()

Date                                                    0
btc_market_price                                        0
btc_total_bitcoins                                     27
btc_market_cap                                          0
btc_trade_volume                                       21
btc_blocks_size                                        29
btc_avg_block_size                                      0
btc_n_orphaned_blocks                                   0
btc_n_transactions_per_block                            0
btc_median_confirmation_time                           12
btc_hash_rate                                           0
btc_difficulty                                         16
btc_miners_revenue                                      0
btc_transaction_fees                                   10
btc_cost_per_transaction_percent                        0
btc_cost_per_transaction                                0
btc_n_unique_addresses                                  0
btc_n_transact

In [9]:
data.corr()

btc_market_price  \
btc_market_price                                            1.000000   
btc_total_bitcoins                                          0.392474   
btc_market_cap                                              0.999784   
btc_trade_volume                                            0.868813   
btc_blocks_size                                             0.674507   
btc_avg_block_size                                          0.544033   
btc_n_orphaned_blocks                                      -0.076400   
btc_n_transactions_per_block                                0.544125   
btc_median_confirmation_time                                0.275250   
btc_hash_rate                                               0.920876   
btc_difficulty                                              0.916925   
btc_miners_revenue                                          0.986732   
btc_transaction_fees                                        0.806595   
btc_cost_per_transaction_percent                           -0.013517   
btc_cost_per_transaction                                    0.815507   
btc_n_unique_addresses                                      0.663917   
btc_n_transactions                                          0.569603   
btc_n_transactions_total                                    0.680048   
btc_n_transactions_excluding_popular                        0.558416   
btc_n_transactions_excluding_chains_longer_than...          0.567281   
btc_output_volume                                           0.111734   
btc_estimated_transaction_volume                            0.050894   
btc_estimated_transaction_volume_usd                        0.968308   

                                                    btc_total_bitcoins  \
btc_market_price                                              0.392474   
btc_total_bitcoins                                            1.000000   
btc_market_cap                                                0.384606   
btc_trade_volume                                              0.285815   
btc_blocks_size                                               0.779705   
btc_avg_block_size                                            0.851554   
btc_n_orphaned_blocks                                         0.274925   
btc_n_transactions_per_block                                  0.831414   
btc_median_confirmation_time                                  0.668119   
btc_hash_rate                                                 0.488668   
btc_difficulty                                                0.497510   
btc_miners_revenue                                            0.383108   
btc_transaction_fees                                          0.472122   
btc_cost_per_transaction_percent                             -0.079864   
btc_cost_per_transaction                                      0.372758   
btc_n_unique_addresses                                        0.820595   
btc_n_transactions                                            0.832865   
btc_n_transactions_total                                      0.782652   
btc_n_transactions_excluding_popular                          0.814721   
btc_n_transactions_excluding_chains_longer_than...            0.800405   
btc_output_volume                                             0.290952   
btc_estimated_transaction_volume                              0.211814   
btc_estimated_transaction_volume_usd                          0.387920   

                                                    btc_market_cap  \
btc_market_price                                          0.999784   
btc_total_bitcoins                                        0.384606   
btc_market_cap                                            1.000000   
btc_trade_volume                                          0.869256   
btc_blocks_size                                           0.672918   
btc_avg_block_size                                        0.541357   
btc_n_orphaned_blocks                                   

In [10]:
data_2 = data.ffill().bfill()

In [11]:
data_2.isnull().sum()

Date                                                   0
btc_market_price                                       0
btc_total_bitcoins                                     0
btc_market_cap                                         0
btc_trade_volume                                       0
btc_blocks_size                                        0
btc_avg_block_size                                     0
btc_n_orphaned_blocks                                  0
btc_n_transactions_per_block                           0
btc_median_confirmation_time                           0
btc_hash_rate                                          0
btc_difficulty                                         0
btc_miners_revenue                                     0
btc_transaction_fees                                   0
btc_cost_per_transaction_percent                       0
btc_cost_per_transaction                               0
btc_n_unique_addresses                                 0
btc_n_transactions             

In [12]:
data_2.dtypes

Date                                                    object
btc_market_price                                       float64
btc_total_bitcoins                                     float64
btc_market_cap                                         float64
btc_trade_volume                                       float64
btc_blocks_size                                        float64
btc_avg_block_size                                     float64
btc_n_orphaned_blocks                                    int64
btc_n_transactions_per_block                           float64
btc_median_confirmation_time                           float64
btc_hash_rate                                          float64
btc_difficulty                                         float64
btc_miners_revenue                                     float64
btc_transaction_fees                                   float64
btc_cost_per_transaction_percent                       float64
btc_cost_per_transaction                               

In [13]:
x_data = data_2.drop(['Date', 'btc_market_price'], axis=1)
x_data.head()

btc_total_bitcoins  btc_market_cap  btc_trade_volume  btc_blocks_size  \
0           2043200.0             0.0               0.0              0.0   
1           2054650.0             0.0               0.0              0.0   
2           2063600.0             0.0               0.0              0.0   
3           2074700.0             0.0               0.0              0.0   
4           2085400.0             0.0               0.0              0.0   

   btc_avg_block_size  btc_n_orphaned_blocks  btc_n_transactions_per_block  \
0            0.000235                      0                           1.0   
1            0.000241                      0                           1.0   
2            0.000228                      0                           1.0   
3            0.000218                      0                           1.0   
4            0.000234                      0                           1.0   

   btc_median_confirmation_time  btc_hash_rate  btc_difficulty  \
0                           0.0       0.000029        2.527738   
1                           0.0       0.000029        2.527738   
2                           0.0       0.000023        2.527738   
3                           0.0       0.000028        2.527738   
4                           0.0       0.000027        2.527738   

                   ...                   btc_cost_per_transaction_percent  \
0                  ...                                          31.781022   
1                  ...                                         154.463801   
2                  ...                                        1278.516635   
3                  ...                                       22186.687990   
4                  ...                                         689.179876   

   btc_cost_per_transaction  btc_n_unique_addresses  btc_n_transactions  \
0                       0.0                     241                 244   
1                       0.0                     234                 235   
2                       0.0                     185                 183   
3                       0.0                     224                 224   
4                       0.0                     218                 218   

   btc_n_transactions_total  btc_n_transactions_excluding_popular  \
0                     41240                                   244   
1                     41475                                   235   
2                     41658                                   183   
3                     41882                                   224   
4                     42100                                   218   

   btc_n_transactions_excluding_chains_longer_than_100  btc_output_volume  \
0                                                244             65173.13   
1                                                235             18911.74   
2                                                183              9749.98   
3                                                224             11150.03   
4                                                218             12266.83   

   btc_estimated_transaction_volume  btc_estimated_transaction_volume_usd  
0                           36500.0                                   0.0  
1                            7413.0                                   0.0  
2                             700.0                                   0.0  
3                              50.0                                   0.0  
4                            1553.0                                   0.0  

[5 rows x 22 columns]

In [14]:
y_data = data_2['btc_market_price']
y_data.describe()

count     2906.000000
mean       839.104218
std       2304.972497
min          0.000000
25%          6.653465
50%        235.130000
75%        594.191164
max      19498.683330
Name: btc_market_price, dtype: float64

# finally created all final datasets


# scaling x dataset


In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_data_scaled = scaler.fit_transform(x_data)

# for KNN

In [17]:
# plot k-NN regression on sample dataset for different values of K

from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsRegressor

for K in [1, 3, 7, 15, 55]:
    scores_knn = cross_val_score(KNeighborsRegressor(n_neighbors = K), x_data_scaled, y_data, cv = 5)
    print(scores_knn)


[-0.24717899 -6.34951462 -0.16832938 -2.1202622  -0.39904766]
[-0.2123213  -5.98359071 -0.17781827 -1.89943112 -0.40782941]
[-0.15625421 -5.80237314 -0.22296534 -1.79413664 -0.41540001]
[-0.124966   -5.64229721 -0.34189877 -1.61137254 -0.42578528]
[-0.0163555  -5.49744556 -0.63223927 -1.72184515 -0.4602248 ]


In [24]:
from sklearn.model_selection import GridSearchCV

knn = KNeighborsRegressor()
param_grid = {'n_neighbors':[1, 3, 7, 15, 55]}

grid_search = GridSearchCV(knn, param_grid, cv = 5)
grid_search.fit(x_data_scaled, y_data)

GridSearchCV(cv=5, error_score='raise',
       estimator=KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_neighbors': [1, 3, 7, 15, 55]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [25]:
print('Best parameters{}'.format(grid_search.best_params_))
print('Best score {:.2f}'.format(grid_search.best_score_))

Best parameters{'n_neighbors': 15}
Best score -1.63


In [28]:
results = pd.DataFrame(grid_search.cv_results_)

C:\Users\andre\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\andre\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\andre\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\andre\Anaconda3\lib\site-packages\sklearn\utils\

In [71]:
# linear reg
from sklearn.linear_model import LinearRegression

linreg = LinearRegression().fit(x_train_scaled, y_train)

print('R-squared score (training): {:.3f}'
     .format(linreg.score(x_train_scaled, y_train)))
print('R-squared score (test): {:.3f}'
     .format(linreg.score(x_test_scaled, y_test)))


R-squared score (training): 1.000
R-squared score (test): 1.000


In [87]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train_scaled, y_train)
print("R squared Training : " + str(lr.score(x_train_scaled , y_train)))
print("R squared Test : " + str(lr.score(x_test_scaled , y_test)))


R squared Training : 0.99995764035
R squared Test : 0.999958082859


In [89]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(lr, x_train_scaled, y_train, cv = 5)
print(scores)

[ 0.99993915  0.99995689  0.99996456  0.99996229  0.99995041]


In [90]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(lr, x_test_scaled, y_test, cv = 5)
print(scores)

[ 0.99995206  0.99993498  0.99996631  0.99995462  0.99994025]


In [94]:
np.mean(scores)

0.99994964496366612

In [21]:
# plot k-NN regression on sample dataset for different values of K

from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsRegressor

for K in [1, 3, 7, 15, 55]:
    scores_knn = cross_val_score(KNeighborsRegressor(n_neighbors = K), x_test_scaled, y_test, cv = 5)
    print(scores_knn)
    
    

[ 0.97542871  0.99684679  0.99577537  0.97666814  0.97116716]
[ 0.9809181   0.9884986   0.98713846  0.98014045  0.97215809]
[ 0.9903014   0.98327214  0.98476516  0.98458379  0.95653161]
[ 0.97541955  0.96089995  0.96145764  0.98915008  0.94923621]
[ 0.6794093   0.67126862  0.65960736  0.76792869  0.7998413 ]


In [ ]:
knnreg = KNeighborsRegressor(n_neighbors = K).fit(x_train_scaled, y_train)
    train_score = knnreg.score(x_train_scaled, y_train)
    test_score = knnreg.score(x_test_scaled, y_test)
    print ("K is " + str(K) + ". Training R^2 = " + str(train_score) + ". Test R^2 = " + str(test_score))

